apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-system
  namespace: notification-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: notifications.example.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway
                port: { number: 3000 }
