{{- if .Values.serviceMonitor.enabled }}
{{- range .Values.services }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  endpoints:
    - port: http
      path: {{ $.Values.config.prometheusMetricsPath }}
      interval: {{ $.Values.serviceMonitor.interval }}
---
{{- end }}
{{- end }}
